### ISSUE TITLE
Randomly repeat html content

### ISSUE THREAD

**Issue by sirowood** [EC-Nordbund/denomailer#12]
**Describe the bug**
**html** body sometimes send repeat content, such as:
_Attend: Yes
Start time: 07:00
End time: 12:00

d: Yes
Start time: 07:00
End time: 12:00_

**To Reproduce**
It seems the bug occurs randomly, and the repeat line also occurs randomly.
`<p>Record date: ${recordDate}</p>
<p>Record time: ${recordTime}</p>
<p>Attend: ${attend ? "Yes": "No"}</p>
<p>Start time: ${startTime}</p>
<p>End time: ${endTime}</p>`

**Expected behavior**

**Logs**
Provide the output of `deno --version`
```
1.20.4
```

**Additional context**
0.8.0 works without this bug.

**Comment by mathe42** [comment]
Could you provide some code?

**Comment by sirowood** [comment]
Hi,

Here it is:
`
<strong>Dear ${name},</strong>
<p>Welcome onboard!</p>
<p>We have created a new account for you as <strong><em>${roleName}
</em></strong></p>
<p>Please use the following information to login for your first time:</p>
<p>Email address: ${email}</p>
<p>Password: ${password}</p>
<p></p>
<p>Best regards,</p>
`

Sebastian Krüger ***@***.***> 于2022年4月13日周三 12:45写道：

**Comment by xCykrix** [comment]
I seem to have a similar case to this. Not sure if it is identical though but I have an email sent that the quotable printable seems to break. I've seen =20 in the pages before which is from the quotable printable. Been struggling to set the HTML content as some part of it always seems to break.

```ts
mailer.send({
        to: email!, // 'user@tld.com'
        from: configuration.mailer.from, // 'Notification <no-reply@tld.com>'
        subject: 'Authentication Request',
        html: this.loginEmailTemplate // new TextDecoder().decode(Deno.readFileSync('./templates/email.html'));
          .replace('_inject0', `https://${configuration.server.domain}/user/authenticate/callback/${eid}/${loginCode}`)
          .replace('_inject1', `https://${configuration.server.domain}/user/fraud/${eid}/${fraudCode}`)
          .replace('_inject2', `https://${configuration.server.domain}/user/unsubscribe/${eid}/${unsubscribeCode}`),
      });
```

![image](https://user-images.githubusercontent.com/12182390/164716822-bb51710d-cc9c-4665-9c23-723619d529c7.png)
![image](https://user-images.githubusercontent.com/12182390/164716926-7edd0f4c-b91d-4f30-9d0a-7c4b60c2404b.png)
![image](https://user-images.githubusercontent.com/12182390/164717759-177e19b7-a769-4e0a-b2b2-2fd62193ddd8.png)
![image](https://user-images.githubusercontent.com/12182390/164717778-e155c4e5-1ed0-4e85-9c91-1c56c043b77f.png)

HTML: https://gist.github.com/xCykrix/00a71d6aaf400630910ed3e0de90b17b
Pic 1/2 are email.html
Pic 3/4 are the other file.

**Comment by mathe42** [comment]
Yes I think it is the encoding but I have problems seeing why... Spaces (=20) are only encoding before a linebreak. When you remove all whitespace before linebreaks this should be fine!?

**Comment by xCykrix** [comment]
If the HTML is minified to absolutely no excess whitespace (one line) it sends in the expected format, but that isn't really viable from a development standpoint to keep it minified across development and production. I have absolutely no experience with quotable printable to think why it is breaking between sending and delivery. It renders fine as an HTML file but once it is encoded and sent it breaks down somewhere along the way.

**Comment by xCykrix** [comment]
Added the "View Original" from Gmail to see if maybe that will shed some light. Seems like potentially some of the equals in the HTML code are causing the issue? Very far out of my realm of expertise but I see `href=3D"..."` where fields like `href="..."` normally should be.

**Comment by mathe42** [comment]
= is encoded to =3D thats fine.

**Comment by mathe42** [comment]
I found 1 Bug. but it is still not fixed :D

**Comment by mathe42** [comment]
OK found the bugs. Now it should be fine. Will release in the next 10 min just want to test some more...

**Comment by xCykrix** [comment]
I'll keep an eye out for it. Thank you! Thought I was going crazy because I couldn't figure out if it was an issue in the HTML or not haha.

**Comment by mathe42** [comment]
released as 0.16.0

**Comment by mathe42** [comment]
2 Bugs:
0. Somehow linebreaks got missinterpreted (I think I encoded them as required) so enabeling better encoding of linebreaks
1. Encoding chars < 16 (for example \n=10 to =A and not to =0A) 
2. Spaces at file end where encoded to =20 and that was later encoded to =3D20 so the = was encoded what was bad...

**Comment by xCykrix** [comment]
@mathe42 
![image](https://user-images.githubusercontent.com/12182390/164730316-01012421-783e-403a-bd87-0cafcbc9a165.png)

v0.16.0 made additional encoding errors it seems. Added original message content at https://gist.github.com/xCykrix/00a71d6aaf400630910ed3e0de90b17b#file-new-original-message

**Comment by mathe42** [comment]
could you send that mail with

```
await client.connect({
  hostname: 'smtp.ethereal.email',
  username: 'ivy.schneider17@ethereal.email',
  password: '7ycUTX366ZZeamxy9D',
  port: 587
})
```

I couldn't reproduce that. And please tell me the output of `deno --version`

**Comment by mathe42** [comment]
I think I know the problem and I fixed it in de65208c259280bbeafbdb2ba7ab9d32e10ab2b6.  Hope `0.16.1` fixes it for you. Is a client encoding problem I think. The way how you implement the decoding of quoted printable the problem could be automaticly fixed.

**Comment by xCykrix** [comment]
Creating my own inbox with Ethereal and sending it via Ethereal gives the expected outcome (also sent inbound to the account via my SMTP server), but if I send it to Gmail or Outlook it has encoding errors. 0.16.1 did not resolve the issue. I'll try to send it via Gmail SMTP to see if perhaps it will have a different result.

Also:
deno 1.21.0 (release, x86_64-unknown-linux-gnu)
v8 10.0.139.17
typescript 4.6.2

**Comment by mathe42** [comment]
created new issue for that will look into it tomorrow. But at least some bugs are fixed ;D
